module Main exposing (..)

import Html exposing (Html)
import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (..)


main =
    div []
        [ h1 [] [ text "folders" ]
        , div [ class "column is-one-third" ]
            [ aside [ class "menu" ]
                [ p [ class "menu-label" ]
                    [ text "General" ]
                , ul [ class "menu-list" ]
                    [ li []
                        [ a [ href "#" ]
                            [ text "Dashboard" ]
                        ]
                    , li []
                        [ a [ href "#" ]
                            [ text "Customers" ]
                        ]
                    ]
                , p [ class "menu-label" ]
                    [ text "Administration" ]
                , ul [ class "menu-list" ]
                    [ li []
                        [ a [ href "#" ]
                            [ text "Team Settings" ]
                        ]
                    , li []
                        [ a [ class "is-active", href "#" ]
                            [ text "Manage Your Team" ]
                        , ul []
                            [ li []
                                [ a [ href "#" ]
                                    [ text "Members" ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Plugins" ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Add a member" ]
                                ]
                            ]
                        ]
                    , li []
                        [ a [ href "#" ]
                            [ text "Invitations" ]
                        ]
                    , li []
                        [ a [ href "#" ]
                            [ text "Authentication" ]
                        ]
                    ]
                , p [ class "menu-label" ]
                    [ text "Transactions" ]
                , ul [ class "menu-list" ]
                    [ li []
                        [ a [ href "#" ]
                            [ text "Payments" ]
                        ]
                    , li []
                        [ a [ href "#" ]
                            [ text "Transfers" ]
                        ]
                    , li []
                        [ a [ href "#" ]
                            [ text "Balance" ]
                        ]
                    ]
                ]
            ]
        ]
